### ISSUE TITLE
Specified method is not supported when converting RTF

### ISSUE THREAD

**Issue by mjonila** [erdomke/RtfPipe#39]
I've tried RtfPipe with some RTF's and it worked great. However I came across one particular RTF, which does not parse. The error thrown is related to the 'pict' element in RTF header ("Specified method is not supported"). 

However even after removing the 'pict' element (and even whole 'header'), the converted html is empty string.

I was unable to fix this problem myself.
I'm adding related RTF.
Please suggest what could be wrong and how could this be fixed.

thanks a lot!
[LTtechdoc.txt](https://github.com/erdomke/RtfPipe/files/4368922/LTtechdoc.txt)

**Comment by erdomke** [comment]
This should be fixed in the latest release.

**Comment by mjonila** [comment]
Thanks! I noticed you added condition in HexBuffer.cs and this fixed the "not supported" error, however, parsing that RTF still does not procude any html output (just empty string).  Sorry for being impatient, but maybe you see where is the problem and could mention it in the comment at least, so I could fix this myself. thanks again!

**Comment by erdomke** [comment]
I'm confused on how you are getting an empty string as I am [generating HTML content](https://github.com/erdomke/RtfPipe/blob/master/RtfPipe.Tests/Files/Issue39.html) from your RTF file which seems to include the main content of the file. Are you taking a particular approach for generating the HTML?

**Comment by mjonila** [comment]
It was my error. Everything is working fine. I get the document parsed correctly. Thanks for your support Eric!
